### ISSUE TITLE
[LLVM] Complete the M68000 backend so it can be merged upstream

### ISSUE THREAD

**Issue by glaubitz** [M680x0/M680x0-llvm#59]
This is a tracker bug for completing the M68000 backend so it can merged upstream. This bug will be used to create a campaign on Bountysource.com.

Since the LLVM project may still reject the completed backend to be merged upstream due to the lack of a dedicated maintainer, the upstream merge should not be considered a requirement to complete the task for the campaign on Bountysource.com.

Please do not close this bug unless the M68000 backend is mature and complete enough to be merged upstream. Whether that state has been reached shall be subject to reviews by LLVM upstream and/or the backers of the Bountysource.com campaign.

**Comment by segabor** [comment]
Just curious when / if it will happen. Is this repo active?

**Comment by glaubitz** [comment]
The discussion and the development happens on https://reviews.llvm.org/. Go there and search for "M68k".

And, yes, we're making fantastic progress \o/.

**Comment by segabor** [comment]
@glaubitz amazing news! However I can't find the page you are referring. Reviews site did not yield any result for M68k or even Motorola keywords. UPDATE: now I can see what you mentioned above. Unfortunately search on mobile did not find anything but in desktop browser it does.

**Comment by ghost** [comment]
@segabor, for your convenience, copied here from https://www.bountysource.com/issues/90829856-llvm-complete-the-m68000-backend-so-it-can-be-merged-upstream -> updates -> mschockwave)

>The upstream process has been kicked off! Here are the patch list: 
1. https://reviews.llvm.org/D88385 
2. https://reviews.llvm.org/D88386 
3. https://reviews.llvm.org/D88389 
4. https://reviews.llvm.org/D88390 
5. https://reviews.llvm.org/D88391 
6. https://reviews.llvm.org/D88392 
7. https://reviews.llvm.org/D88393 
8. https://reviews.llvm.org/D88394 

>In addition, here is the RFC thread on the mailing list: 

http://lists.llvm.org/pipermail/llvm-dev/2020-September/145320.html 

>And here is the board that tracks the upstream progress: 

https://github.com/M680x0/M680x0-mono-repo/projects

**Comment by segabor** [comment]
@abebeos thanks for the update! I was about to ask you if there's an easy way to build the whole stuff but I see now there is a dedicated repository to test the code.
Happy New Year!

**Comment by glaubitz** [comment]
The backend has now landed upstream which means this task has been completed:

> https://github.com/llvm/llvm-project/tree/main/llvm/lib/Target/M68k

Closing so that the Bountysource campaign is notified about this achievment as well.

**Comment by segabor** [comment]
Amazing news! I never thought it would make it to the mainline.

Now I really want to try it out. Boring and lazy question: what is the easiest way to make it run on my macOS? I started reading articles on setting up an LLVM cross compiler but I appreciate any help including basic setup instructions.
Thanks!

**Comment by glaubitz** [comment]
See this discussion, for example: https://stackoverflow.com/questions/62523093/compile-llvm-from-sources-on-macos-catalina-how-to-solve-stdio-h-not-found

The official documentation should help as well: https://llvm.org/docs/GettingStarted.html

**Comment by segabor** [comment]
Thanks a lot! I was unsure if I built LLVM from scratch it would contain m68k target as well.
